In [2]:
import numpy as np
import pandas as pd

CREATING DATAFRAMES WITH DICTONARY

In [3]:
data = {
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

 CREATING DATAFRAMES WITH DATA LIST

In [7]:
data_list = [
    ['John',	28,	'New York',	65000],
    ['Anna',	32	,'Paris',	70000],
    ['Peter',29	,'Berlin',	62000],
    ['Linda',	28,	'London',	85000],

]
df2 =pd.DataFrame(data_list) #default column name 
print(df2)
columns = ["Name","Age","City","Salary"] # by this we can give headers to the list 
df2 = pd.DataFrame(data_list,columns=columns)
print("\n",df2)

       0   1         2      3
0   John  28  New York  65000
1   Anna  32     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  28    London  85000

     Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   28    London   85000

SELECTION AND INDEXING OF COLUMNS

In [9]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [11]:
df2[['Name','Age']]

    Name  Age
0   John   28
1   Anna   32
2  Peter   29
3  Linda   28

CREATING NEW COLUMN

In [ ]:
df2["Designation"] = ["CA","Architech","Doctor","Designer"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          CA
1   Anna   32     Paris   70000   Architech
2  Peter   29    Berlin   62000      Doctor
3  Linda   28    London   85000    Designer

REMOVING A COLUMN

In [ ]:
df2.drop('Designation',axis=1) #drop  does not remove the data in real from database (axis=0 for row,axis=1 for col)
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          CA
1   Anna   32     Paris   70000   Architech
2  Peter   29    Berlin   62000      Doctor
3  Linda   28    London   85000    Designer

In [ ]:
df2.drop('Designation',axis=1,inplace=True) #inplace completelty removes the data from database
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   28    London   85000

SELECTING A ROW

In [ ]:
df2.loc[0]  #loc means location

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df2.loc[[0,1]] #selecting multiple rows

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   32     Paris   70000

SELECTING SUBSETS OF A ROWS AND COLUMNS

In [ ]:
df2.loc[[0,1]][["City","Salary"]] #first we select rows and then columns
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   28

CONDITIONAL SELECTION

In [17]:
#I only want to see whose age is above 30

df2[df2["Age"] > 30]

   Name  Age   City  Salary
1  Anna   32  Paris   70000

In [ ]:
#I only want people whose age is above 20 and their city must be paris

df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   32  Paris   70000